#!/bin/bash

# Collect all parameters in order and build a file name prefix
PREFIX=""
while [[ $# > 1 ]]; do
    PREFIX=${PREFIX}$1.
    shift
done

if [ $# > 0 ]; then
    ns=`xargs -0 -L1 -a /proc/${1}/environ | grep -e "^NAMESPACE_ID" | cut -f2 -d'='`
    if [ ! -z ${ns} ]; then
        PREFIX=${PREFIX}${ns}.
    fi
fi

/bin/gzip -1 - > /var/core/${PREFIX}core.gz

# coredump_gen_handler invokes techsupport if all the other required conditions are met
# explicitly passing in the env vars because coredump-compress's namespace doesn't have these set by default
setsid $(echo > /tmp/coredump_gen_handler.log;
         export PYTHONPATH=$PYTHONPATH:/usr/local/lib/python3.7/dist-packages/;
         export PATH=$PATH:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin;
         python3 /usr/local/bin/coredump_gen_handler.py ${PREFIX}core.gz &>> /tmp/coredump_gen_handler.log) &
